### ISSUE TITLE
[Turma 1 - 08/05] Coloque aqui o link para o seu exercício:

### ISSUE THREAD

**Issue by marcel0ll** [marcel0ll/curso-git#1]
Essa issue servirá para avaliação do curso no dia 05/08, siga o exemplo abaixo:

**Comment by otaviogui** [comment]
Repositório: https://github.com/otaviogui/curso-git-ex-1

**Comment by andreyhashi** [comment]
[Turma 1 - 08/05] https://github.com/andreyhashi/curso-git-ex-1

**Comment by igorlmgx** [comment]
https://github.com/igorlmgx/curso-git-ex-1/

**Comment by francisco-groppo** [comment]
https://github.com/francisco-groppo/curso-git-ex-1

**Comment by klausborges** [comment]
https://github.com/spaceporn/curso-git-ex-1

**Comment by vpereira13** [comment]
https://github.com/vpereira13/curso-git-ex-1

**Comment by IvanCalvo** [comment]
https://github.com/IvanCalvo/curso-git-ex-1/

**Comment by LucasSonego** [comment]
https://github.com/LucasSonego/curso-git-ex-1

**Comment by Vitor178** [comment]
https://github.com/Vitor178/curso-git-ex-1

**Comment by danielfarah54** [comment]
https://github.com/danielfarah54/curso-git-ex-1

**Comment by LucasVD23** [comment]
https://github.com/LVD2304/curso-git-ex-1

**Comment by CarlosFontaneli** [comment]
https://github.com/CarlosFontaneli/-curso-git-ex-1-.git

**Comment by playboost** [comment]
https://github.com/playboost/curso-git-ex-1

**Comment by marcel0ll** [comment]
https://github.com/marcel0ll/curso-git-ex-1

**Comment by guivbalduino** [comment]
https://github.com/Vilardino/curso-git-ex-1

**Comment by PedroGSantos** [comment]
https://github.com/PedroGSantos/curso-git-ex-1/tree/master

**Comment by PedroGSantos** [comment]
https://github.com/PedroGSantos/curso-git-ex-1

**Comment by FabioAmorim1501** [comment]
https://github.com/FabioAmorim1501/curso-git-ex-1

**Comment by Cristian808** [comment]
https://github.com/Cristian808/pc1-curso-git-ex-1

**Comment by Igz72** [comment]
https://github.com/Igz72/curso-git-ex-1

**Comment by Matheus-Bueno** [comment]
https://github.com/Matheus-Bueno/curso-git-ex-1.git

**Comment by luana-q-g** [comment]
https://github.com/luana-q-g/curso-git-ex-1.git

**Comment by zevictordantas** [comment]
https://github.com/zevictordantas/curso-git-ex-1
